services:
    app:
        build:
            context: .
        container_name: hexa-shop-app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - hexa-shop-network

    mysql:
        image: mysql:8.0
        container_name: hexa-shop-mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: hexa_shop_db
            MYSQL_USER: hexa_shop_user
            MYSQL_PASSWORD: userpassword
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - hexa-shop-network

    nginx:
        image: nginx:latest
        container_name: hexa-shop-nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www
        depends_on:
            - app
        networks:
            - hexa-shop-network

    mailpit:
        image: axllent/mailpit
        container_name: mailpit
        ports:
            - "8025:8025"
            - "1025:1025"
        networks:
            - hexa-shop-network

networks:
    hexa-shop-network:
        driver: bridge

volumes:
    mysql_data:
